// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnqdnsscbbkbrqengcjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRucWRuc3NjYmJrYnJxZW5nY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTkzNjgsImV4cCI6MjA3MDkzNTM2OH0.S9su_QYpxW-dHX51Yz6R5ON1aEmr22wLm-0oJIhN3wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});